### ISSUE TITLE
solved: Aqara Wall Switch Double Key

### ISSUE THREAD

**Issue by Werner-G** [hobbyquaker/node-red-contrib-zigbee#82]
I'm using the excellent AQARA Wall switch Double Key (https://www.gearbest.com/alarm-systems/pp_610096.html). I have no problems to integrate with the ZIGBEE-Node and to switch with one key only. But I have no idea how to use both left and right keys, and to read out state_left and state_right.  Is there anybody who could kindly post a working example here?

**Comment by Sineos** [comment]
Try to use the command node instead of the converter. You need to publish to endpoint 1 for left and to endpoint 2 for right. E.g.:

![grafik](https://user-images.githubusercontent.com/4459312/71312387-8d88ca80-242a-11ea-9687-cfe0c1557987.png)

Use a change node to generate the command:
![grafik](https://user-images.githubusercontent.com/4459312/71312404-bc9f3c00-242a-11ea-8a68-5ddbebeaf667.png)

**Comment by Werner-G** [comment]
Great! This works fine, thank you! How do you read out state - with the event node?

**Comment by Sineos** [comment]
@Werner-G 
You are welcome and yes use the event node.

@hobbyquaker 
Reference to #73 and https://github.com/Koenkk/zigbee-herdsman-converters/issues/756
There seems to be something wrong with the way how these devices are handled when using the converter. I suspect it is due to the special topic structure but have not verified under a bare metal zigbee2mqtt.

**Comment by Werner-G** [comment]
I didn't manage to read out the event mode. I used the MQTT-node instead:

![Screenshot_2019-12-23 Node-RED 192 168 1 34](https://user-images.githubusercontent.com/30697956/71348511-f9734c00-256c-11ea-9cc2-aa8c3d40a6bf.png)

Thanks for your help, and Happy Christmas!
